---
title: "Hurricane Maria Mortality Study Response to Inquiries"
output: 
  html_document: default
  github_document: default
  pdf_document: default
---

Hurricane Maria Mortality Study (NEJM online, Kishore et al., May 29 2018)

Available online: https://www.nejm.org/doi/full/10.1056/NEJMsa1803972

Last updated: `r format(Sys.time(), "%B %d, %Y")`

## Response to Inquiries

1. In table S4 of the supplementary appendix, we refer to the “average monthly mortality rate.” This can perhaps be more clearly be stated as the number of deaths per 1000 people per unit of time from September 20th until December 31st.

1. On page 3 of the manuscript we refer to the variable $R_{before}$. We did not use this variable in our main calculations and referred to it in the text to highlight that our rate is separate from this value and only encompases the period after September 20th. We do calculate this statistic in the supplementary appendix. Similar to the $R_{after}$ it is calculated as follows

$$
R_{before}=\frac{\text{deaths}_{before}}{\text{population} \times \frac{263}{365}}
$$ 

In this case, $\text{deaths}_{before}$ is the count of deaths in our survey from January 1st until September 19th (263 days).
